-- 古堅南FC Ver.4.1 第1弾：AI利用履歴（任意）
create table if not exists public.ai_analysis_logs (
  id bigint generated by default as identity primary key,
  analysis_type text not null check (analysis_type in ('chat','match','tactics')),
  request_data jsonb not null default '{}'::jsonb,
  response_text text,
  created_at timestamptz not null default now()
);
alter table public.ai_analysis_logs enable row level security;
-- 第1弾ではフロントから直接書き込ませず、AIサーバー経由の利用を推奨します。
