const $=id=>document.getElementById(id),uid=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());
let state=JSON.parse(localStorage.getItem('sva_pro_all')||'null')||{settings:{teamName:'',season:new Date().getFullYear().toString(),color:'#18bce8',message:'',supabaseUrl:'',supabaseKey:'',aiUrl:''},players:[],matches:[],events:[],highlights:[]};
let selected='',pending='',pos=null,mapMode='heat';
const types=['ゴール','アシスト','シュート','枠内シュート','枠外シュート','パス成功','パス失敗','クロス','ドリブル成功','ドリブル失敗','ボール奪取','インターセプト','ボールロスト','クリア','CK','FK','PK','好プレー','ファウル','セーブ'];
const posTypes=new Set(['ゴール','シュート','枠内シュート','枠外シュート','パス成功','パス失敗','クロス','ドリブル成功','ドリブル失敗','ボール奪取','インターセプト','ボールロスト','クリア','CK','FK','PK','好プレー','セーブ']);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=s=>{s=Math.max(0,s||0);let m=Math.floor(s/60),q=Math.floor(s%60),c=Math.floor((s%1)*100);return `${String(m).padStart(2,'0')}:${String(q).padStart(2,'0')}.${String(c).padStart(2,'0')}`};
function save(){localStorage.setItem('sva_pro_all',JSON.stringify(state));renderAll()}
function view(n){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===n));$(`${n}View`).classList.add('active');if(n==='maps')drawMap();if(n==='reports')renderReport()}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>view(t.dataset.view));
function setRole(r){document.body.classList.toggle('parent',r==='parent');document.body.classList.toggle('staffmode',r==='staff');localStorage.setItem('sva_pro_role',r);let a=document.querySelector('.view.active');if(a&&getComputedStyle(a).display==='none')view('dashboard')}
$('role').value=localStorage.getItem('sva_pro_role')||'coach';$('role').onchange=e=>setRole(e.target.value);setRole($('role').value);
function pName(p){return `${p.number?`${p.number} `:''}${p.name||'未入力'}`}
function addPlayer(){state.players.push({id:uid(),number:'',name:'',grade:'',position:'MF'});save()}
function addMatch(){state.matches.push({id:uid(),date:new Date().toISOString().slice(0,10),opponent:'',competition:'',gf:0,ga:0,season:state.settings.season});save()}
$('addPlayer').onclick=addPlayer;$('addMatch').onclick=addMatch;
function renderPlayers(){$('playerEditor').innerHTML='';state.players.forEach(p=>{let r=document.createElement('div');r.className='player-row';r.innerHTML=`<label>背番号<input value="${esc(p.number)}"></label><label>名前<input value="${esc(p.name)}"></label><label>学年<input value="${esc(p.grade)}"></label><label>位置<select><option>GK</option><option>DF</option><option>MF</option><option>FW</option></select></label><button>削除</button>`;let ins=r.querySelectorAll('input');['number','name','grade'].forEach((k,i)=>ins[i].oninput=e=>{p[k]=e.target.value;localStorage.setItem('sva_pro_all',JSON.stringify(state));renderQuick();updateSelects()});let s=r.querySelector('select');s.value=p.position;s.onchange=e=>{p.position=e.target.value;localStorage.setItem('sva_pro_all',JSON.stringify(state))};r.querySelector('button').onclick=()=>{state.players=state.players.filter(x=>x.id!==p.id);save()};$('playerEditor').appendChild(r)});renderQuick()}
function renderMatches(){$('matchEditor').innerHTML='';state.matches.forEach(m=>{let r=document.createElement('div');r.className='match-row';r.innerHTML=`<label>日付<input type="date" value="${m.date}"></label><label>対戦相手<input value="${esc(m.opponent)}"></label><label>大会<input value="${esc(m.competition)}"></label><label>得点<input type="number" value="${m.gf}"></label><label>失点<input type="number" value="${m.ga}"></label><button>削除</button>`;let ins=r.querySelectorAll('input');['date','opponent','competition','gf','ga'].forEach((k,i)=>ins[i].oninput=e=>{m[k]=e.target.type==='number'?Number(e.target.value):e.target.value;localStorage.setItem('sva_pro_all',JSON.stringify(state));renderDashboard();renderSeason();updateSelects()});r.querySelector('button').onclick=()=>{state.matches=state.matches.filter(x=>x.id!==m.id);state.events=state.events.filter(e=>e.matchId!==m.id);save()};$('matchEditor').appendChild(r)});updateSelects()}
function updateSelects(){let mo=state.matches.map(m=>`<option value="${m.id}">${esc(m.date)} ${esc(m.opponent||'未入力')}</option>`).join(''),po=state.players.map(p=>`<option value="${p.id}">${esc(pName(p))}</option>`).join('');['analysisMatch','mapMatch'].forEach(id=>$(id).innerHTML=mo||'<option value="">試合を登録</option>');$('mapPlayer').innerHTML='<option value="">全選手</option>'+po;$('seasonFilter').innerHTML=[...new Set(state.matches.map(m=>m.season||m.date.slice(0,4)))].map(s=>`<option>${s}</option>`).join('')||`<option>${state.settings.season}</option>`;updateTargets()}
function renderQuick(){$('quickPlayers').innerHTML='';state.players.forEach(p=>{let b=document.createElement('button');b.className='chip'+(selected===p.id?' active':'');b.textContent=pName(p);b.onclick=()=>{selected=p.id;$('selectedPlayer').textContent=`選択中：${pName(p)}`;renderQuick()};$('quickPlayers').appendChild(b)})}
$('clearPlayer').onclick=()=>{selected='';$('selectedPlayer').textContent='選手未選択';renderQuick()};
function renderButtons(){$('eventButtons').innerHTML='';types.forEach(t=>{let b=document.createElement('button');b.textContent=t;b.onclick=()=>begin(t);$('eventButtons').appendChild(b)})}
function begin(t){if(posTypes.has(t)){pending=t;pos=null;$('posTitle').textContent=`${t}の位置`;$('posText').textContent='位置未選択';$('posSave').disabled=true;drawPitch($('posPitch'));$('posDialog').showModal()}else record(t,null)}
function record(t,p){let mid=$('analysisMatch').value;if(!mid)return alert('試合を登録してください。');let pl=state.players.find(x=>x.id===selected);state.events.push({id:uid(),matchId:mid,playerId:pl?.id||'',playerName:pl?pName(pl):'',type:t,period:$('period').value,time:video.currentTime||0,comment:$('comment').value.trim(),position:p});$('comment').value='';save()}
$('posPitch').onclick=e=>{let r=e.target.getBoundingClientRect();pos={x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};$('posText').textContent=`X ${Math.round(pos.x*100)}% / Y ${Math.round(pos.y*100)}%`;$('posSave').disabled=false;drawPitch($('posPitch'),pos)};$('posSave').onclick=()=>{record(pending,pos);$('posDialog').close()};$('posSkip').onclick=()=>{record(pending,null);$('posDialog').close()};$('posClose').onclick=()=>$('posDialog').close();
function renderTimeline(){let mid=$('analysisMatch').value,l=state.events.filter(e=>!mid||e.matchId===mid).sort((a,b)=>a.time-b.time);$('timeline').innerHTML=l.map(e=>`<div class="timeline-item"><button data-j="${e.time}">${fmt(e.time)}</button><div><b>${esc(e.type)}</b><p class="note">${esc(e.playerName||'選手未選択')}・${esc(e.period)} ${esc(e.comment)}</p></div><button data-d="${e.id}">削除</button></div>`).join('')||'<p class="note">記録なし</p>';document.querySelectorAll('[data-j]').forEach(b=>b.onclick=()=>{video.currentTime=Math.max(0,Number(b.dataset.j)-5);video.play()});document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{state.events=state.events.filter(e=>e.id!==b.dataset.d);save()})}
$('analysisMatch').onchange=renderTimeline;$('undo').onclick=()=>{let mid=$('analysisMatch').value,last=state.events.filter(e=>e.matchId===mid).at(-1);if(last){state.events=state.events.filter(e=>e.id!==last.id);save()}};$('highlight').onclick=()=>{state.highlights.push({id:uid(),matchId:$('analysisMatch').value,time:video.currentTime||0,label:$('comment').value||'ハイライト'});save();alert('追加しました')};
const video=$('video');$('videoInput').onchange=e=>{let f=e.target.files?.[0];if(f)video.src=URL.createObjectURL(f)};video.ontimeupdate=()=>$('time').textContent=fmt(video.currentTime);$('playPause').onclick=()=>video.paused?video.play():video.pause();$('prevFrame').onclick=()=>video.currentTime=Math.max(0,video.currentTime-1/30);$('nextFrame').onclick=()=>video.currentTime+=1/30;$('rate').onchange=e=>video.playbackRate=Number(e.target.value);document.querySelectorAll('[data-seek]').forEach(b=>b.onclick=()=>video.currentTime=Math.max(0,video.currentTime+Number(b.dataset.seek)));
function drawPitch(c,mark){let x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);x.fillStyle='#087044';x.fillRect(0,0,w,h);x.strokeStyle='#fff';x.lineWidth=3;let m=w*.05;x.strokeRect(m,m,w-2*m,h-2*m);x.beginPath();x.moveTo(w/2,m);x.lineTo(w/2,h-m);x.stroke();x.beginPath();x.arc(w/2,h/2,h*.12,0,Math.PI*2);x.stroke();x.strokeRect(m,h*.25,w*.17,h*.5);x.strokeRect(w-m-w*.17,h*.25,w*.17,h*.5);if(mark){x.fillStyle='#ffe600';x.beginPath();x.arc(mark.x*w,mark.y*h,12,0,Math.PI*2);x.fill()}}
function drawMap(){let c=$('pitch'),x=c.getContext('2d');drawPitch(c);let es=state.events.filter(e=>e.position&&(!$('mapMatch').value||e.matchId===$('mapMatch').value)&&(!$('mapPlayer').value||e.playerId===$('mapPlayer').value)&&(!$('mapPeriod').value||e.period===$('mapPeriod').value));if(mapMode==='shots')es=es.filter(e=>['ゴール','シュート','枠内シュート','枠外シュート'].includes(e.type));if(mapMode==='passes')es=es.filter(e=>['パス成功','パス失敗','クロス'].includes(e.type));if(mapMode==='loss')es=es.filter(e=>e.type==='ボールロスト');es.forEach(e=>{let px=e.position.x*c.width,py=e.position.y*c.height;if(mapMode==='heat'){let g=x.createRadialGradient(px,py,2,px,py,45);g.addColorStop(0,'rgba(255,60,20,.7)');g.addColorStop(.5,'rgba(255,190,0,.35)');g.addColorStop(1,'rgba(255,255,0,0)');x.fillStyle=g;x.beginPath();x.arc(px,py,45,0,Math.PI*2);x.fill()}else{x.fillStyle=e.type==='ゴール'?'#ffe600':e.type.includes('成功')?'#25d7ff':e.type.includes('失敗')||e.type==='ボールロスト'?'#ff7777':'#fff';x.beginPath();x.arc(px,py,9,0,Math.PI*2);x.fill()}});$('legend').textContent=`表示件数：${es.length}`}
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{mapMode=b.dataset.mode;document.querySelectorAll('.mode').forEach(x=>x.classList.remove('primary'));b.classList.add('primary');drawMap()});['mapMatch','mapPlayer','mapPeriod'].forEach(id=>$(id).onchange=drawMap);
function renderDashboard(){let ms=state.matches,w=ms.filter(m=>m.gf>m.ga).length,g=ms.reduce((n,m)=>n+m.gf,0),a=ms.reduce((n,m)=>n+m.ga,0);$('teamTitle').textContent=state.settings.teamName||'チーム名未設定';$('seasonTitle').textContent=`${state.settings.season} シーズン`;$('kMatch').textContent=ms.length;$('kWin').textContent=w;$('kGoal').textContent=g;$('kAgainst').textContent=a;$('kRate').textContent=ms.length?Math.round(w/ms.length*100)+'%':'0%';$('kPlayers').textContent=state.players.length;$('recent').innerHTML=[...ms].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map(m=>`<div class="list-item"><span>${m.date}</span><b>${esc(m.opponent)}</b><strong>${m.gf}-${m.ga}</strong></div>`).join('')||'<p class="note">試合なし</p>';let sc={};state.events.filter(e=>e.type==='ゴール').forEach(e=>sc[e.playerName||'未選択']=(sc[e.playerName||'未選択']||0)+1);$('ranking').innerHTML=Object.entries(sc).sort((a,b)=>b[1]-a[1]).map(([n,v],i)=>`<div class="rank"><b>${i+1}</b><span>${esc(n)}</span><strong>${v}</strong></div>`).join('')||'<p class="note">得点なし</p>';$('message').value=state.settings.message||'';$('messageView').textContent=state.settings.message||'お知らせなし';let ps=state.events.filter(e=>e.type==='パス成功').length,pf=state.events.filter(e=>e.type==='パス失敗').length,shots=state.events.filter(e=>['ゴール','シュート','枠内シュート','枠外シュート'].includes(e.type)).length,win=state.events.filter(e=>['ボール奪取','インターセプト'].includes(e.type)).length;let t=[];if(ps+pf)t.push(`パス成功率は${Math.round(ps/(ps+pf)*100)}%です。`);if(shots<5)t.push('シュート数を増やす余地があります。');else t.push('積極的にシュートまで持ち込めています。');if(win>=8)t.push('守備でのボール奪取が機能しています。');$('aiSummary').textContent=t.join(' ')||'解析記録が増えるとコメントを表示します。'}
$('message').oninput=e=>{state.settings.message=e.target.value;localStorage.setItem('sva_pro_all',JSON.stringify(state));$('messageView').textContent=e.target.value};
function renderSeason(){let ms=state.matches.filter(m=>!$('seasonFilter').value||String(m.season||m.date.slice(0,4))===$('seasonFilter').value),w=ms.filter(m=>m.gf>m.ga).length,d=ms.filter(m=>m.gf===m.ga).length,l=ms.filter(m=>m.gf<m.ga).length,g=ms.reduce((n,m)=>n+m.gf,0),a=ms.reduce((n,m)=>n+m.ga,0);$('seasonStats').innerHTML=[['試合',ms.length],['勝',w],['分',d],['敗',l],['得点',g],['失点',a],['得失点',g-a]].map(v=>`<div class="stat">${v[0]}<b>${v[1]}</b></div>`).join('');let co={};ms.forEach(m=>{let k=m.competition||'未分類';co[k]||={m:0,w:0};co[k].m++;if(m.gf>m.ga)co[k].w++});$('competition').innerHTML=Object.entries(co).map(([n,v])=>`<div class="list-item"><b>${esc(n)}</b><span>${v.m}試合</span><strong>${v.w}勝</strong></div>`).join('');let mo={};ms.forEach(m=>{let k=m.date.slice(0,7);mo[k]=(mo[k]||0)+m.gf-m.ga});drawChart($('seasonChart'),Object.entries(mo).sort().map(([label,value])=>({label,value})))}
$('seasonFilter').onchange=renderSeason;
function drawChart(c,s){let x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);x.fillStyle='#09182a';x.fillRect(0,0,w,h);if(!s.length){x.fillStyle='#aaa';x.fillText('データなし',w/2,h/2);return}let max=Math.max(1,...s.map(v=>Math.abs(v.value)));x.strokeStyle='#18bce8';x.lineWidth=5;x.beginPath();s.forEach((v,i)=>{let px=60+i*((w-100)/Math.max(1,s.length-1)),py=h/2-(v.value/max)*(h*.35);i?x.lineTo(px,py):x.moveTo(px,py);x.fillStyle='#fff';x.fillText(v.label,px-25,h-20);x.fillText(String(v.value),px-5,py-10)});x.stroke()}
function updateTargets(){let t=$('reportType').value,h='';if(t==='season')h=`<option>${state.settings.season}</option>`;if(t==='match')h=state.matches.map(m=>`<option value="${m.id}">${m.date} ${esc(m.opponent)}</option>`).join('');if(t==='player')h=state.players.map(p=>`<option value="${p.id}">${esc(pName(p))}</option>`).join('');$('reportTarget').innerHTML=h;renderReport()}
$('reportType').onchange=updateTargets;$('reportTarget').onchange=renderReport;$('reportTitle').oninput=renderReport;
function renderReport(){let t=$('reportType').value,id=$('reportTarget').value,title=$('reportTitle').value||'SOCCER VISION ANALYZER PRO レポート',h=`<h2>${esc(title)}</h2><p>${esc(state.settings.teamName)}／${new Date().toLocaleDateString('ja-JP')}</p>`;if(t==='season'){h+=`<h3>${esc(id)}シーズン</h3><table><tr><th>日付</th><th>相手</th><th>大会</th><th>結果</th></tr>${state.matches.map(m=>`<tr><td>${m.date}</td><td>${esc(m.opponent)}</td><td>${esc(m.competition)}</td><td>${m.gf}-${m.ga}</td></tr>`).join('')}</table>`}if(t==='match'){let m=state.matches.find(x=>x.id===id),es=state.events.filter(e=>e.matchId===id);h+=`<h3>${m?.date} vs ${esc(m?.opponent)}</h3><table><tr><th>時刻</th><th>プレー</th><th>選手</th></tr>${es.map(e=>`<tr><td>${fmt(e.time)}</td><td>${esc(e.type)}</td><td>${esc(e.playerName)}</td></tr>`).join('')}</table>`}if(t==='player'){let p=state.players.find(x=>x.id===id),es=state.events.filter(e=>e.playerId===id),c=x=>es.filter(e=>e.type===x).length;h+=`<h3>${esc(pName(p||{}))}</h3><p>得点 ${c('ゴール')}／アシスト ${c('アシスト')}／シュート ${c('シュート')+c('枠内シュート')}／奪取 ${c('ボール奪取')}</p>`}$('reportPreview').innerHTML=h}
$('print').onclick=()=>window.print();
function renderSettings(){$('teamName').value=state.settings.teamName;$('currentSeason').value=state.settings.season;$('teamColor').value=state.settings.color;$('supabaseUrl').value=state.settings.supabaseUrl;$('supabaseKey').value=state.settings.supabaseKey;$('aiUrl').value=state.settings.aiUrl;$('cloudStatus').textContent=state.settings.supabaseUrl?'接続情報保存済み（実同期は未有効化）':'ローカル保存で動作中'}
$('saveSettings').onclick=()=>{state.settings.teamName=$('teamName').value;state.settings.season=$('currentSeason').value;state.settings.color=$('teamColor').value;save()};$('saveCloud').onclick=()=>{state.settings.supabaseUrl=$('supabaseUrl').value;state.settings.supabaseKey=$('supabaseKey').value;state.settings.aiUrl=$('aiUrl').value;save();alert('保存しました')};
$('backup').onclick=()=>download('SVA_PRO_backup.json',JSON.stringify(state,null,2),'application/json');$('restore').onclick=()=>$('restoreFile').click();$('restoreFile').onchange=e=>{let f=e.target.files?.[0],r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);localStorage.setItem('sva_pro_all',JSON.stringify(state));location.reload()}catch{alert('復元失敗')}};if(f)r.readAsText(f)};
function download(n,t,ty){let b=new Blob(['\ufeff',t],{type:ty}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click()}
$('csv').onclick=()=>{let rows=[['時刻','プレー','選手','時間帯','コメント'],...state.events.map(e=>[fmt(e.time),e.type,e.playerName,e.period,e.comment])];download('analysis.csv',rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv;charset=utf-8')};$('xls').onclick=()=>{let rows=state.events.map(e=>`<tr><td>${fmt(e.time)}</td><td>${esc(e.type)}</td><td>${esc(e.playerName)}</td><td>${esc(e.period)}</td><td>${esc(e.comment)}</td></tr>`).join(''),html=`<html><meta charset="utf-8"><table><tr><th>時刻</th><th>プレー</th><th>選手</th><th>時間帯</th><th>コメント</th></tr>${rows}</table></html>`;download('analysis.xls',html,'application/vnd.ms-excel')};
function renderAll(){document.documentElement.style.setProperty('--accent',state.settings.color||'#18bce8');renderPlayers();renderMatches();renderTimeline();renderDashboard();renderSeason();renderSettings();updateSelects();drawPitch($('posPitch'))}
renderButtons();renderAll();